name: Share Data Between Jobs

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Create data file
        run: echo "Data to share" > shared-data.txt

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Read data file
        run: |
          shared_data=$(cat shared-data.txt)
          echo "Data in the env: $shared_data"
