name: Share Data Between Jobs

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set shared data
        run: echo "Data to share" >> $RUNNER_TEMP/shared-data.txt

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Read shared data
        run: |
          shared_data=$(cat $RUNNER_TEMP/shared-data.txt)
          echo "Data in the env: $shared_data"

