name: Send Email

on:
  push:
    branches:
      - main

jobs:
   send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email using Gmail
        uses: dawidd6/action-send-mail-smtp@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: rakesh.rathore@metacube.com
          password: rpukphitgnihitil
          subject: "GitHub Actions Workflow Completed"
          to: banna.rakesh@gmail.com
          from: rakesh.rathore@metacube.com
          body: |
            The GitHub Actions workflow has completed successfully.
            Scratch Org ID: 
            Scratch Org Username: 
            Scratch Org Password:
            Scratch Org URL: 
