name: Share Data Between Jobs

on: [push]

jobs:
  create-data:
    runs-on: ubuntu-latest
    steps:
      - name: Create data file
        run: echo "Data to share" > data.txt
        env:
          SHARED_DATA: "Data to share"

  read-data:
    needs: create-data
    runs-on: ubuntu-latest
    steps:
      - name: Read data from environment variable
        run: echo "Data in the env:$SHARED_DATA"
